# -*- coding: utf-8 -*-
"""Copy of Madlabs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLhCBQ9Q8za4-3yjx7cQJkjw1QZPpOpo
"""

data=input('Give me an antonym for data:')
adjective=input('Tell me an adjective:')
buzzword=input('Give me a sciency buzzword:')
animal=input('A type of animal (plural):')
thing=input('Some Sciency thing:')
another=input('Another sciency thing:')
sci_adj=input('Sciency adjective:')
job=input('Nonmaterial Scientist Job Description:')

print(f'''{data} Job Description: 
Seeking a {adjective} engineer, able to work on {buzzword} projects with a team of {animal}. 
Key responsibilities: 
- {thing}
- {another}
- Transform {sci_adj} crystals into biochemical material.''')



